# Generated by Django 2.2 on 2021-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramraja_app', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='discripation',
            field=models.CharField(max_length=500),
        ),
    ]
