# Generated by Django 2.2 on 2021-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramraja_app', '0003_auto_20210113_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='discripation',
            field=models.CharField(max_length=255),
        ),
    ]
